name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
    - name: Create conda environement
      run: |
        conda init bash
        conda create -q -n build-IntaRNA -c bioconda gcc_linux-64 gxx_linux-64 boost-cpp viennarna pkgconfig
        conda activate build-IntaRNA
    - name: Script
      run: |
        ##### start IntaRNA build #####
        pwd
        # generate autotools's files 
        bash autotools-init.sh 
        # run configure (without boost checks)
        ./configure --prefix=$HOME/IntaRNA --with-vrna=$HOME/miniconda/envs/build-IntaRNA --with-boost=no --without-zlib
        # compile documentation
        # - make doxygen-doc
        # compile, test and install IntaRNA
        make -j 2 && make tests -j 2 && make install
        ##### check IntaRNA build #####
        # run installed IntaRNA with help output
        $HOME/IntaRNA/bin/IntaRNA -h
